---
title: "PCA_Functional"
author: "DSRovinsky"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(geomorph)  # CRAN v4.0.7
library(shapes)    # CRAN v1.2.7
library(tidyverse) # CRAN v2.0.0
library(svglite)   # CRAN v2.1.3
library(here)      # CRAN v1.0.1
```

```{r Load data}
# Load data produced in "GMM_GPA.Rmd"
load(here("Data", "Processed", "skullLmkSymm.rda"))
load(here("Data", "Processed", "rostralLmkSymm.rda"))
load(here("Data", "Processed", "neuroLmkSymm.rda"))

# Load the labels produced in "GMM_GPA.Rmd"
pointLabels <- readRDS(here("Data", "Processed", "pointLabels.rds"))

```

```{r Labels}
pointLabels$PtCol <- "#fff0e0"
pointLabels$PtCol[pointLabels$Clade == "Metatheria"] <- "#e0f0ff"
pointLabels$PtCol[pointLabels$Family == "Thylacinidae"] <- "#c87ef8" #purple
pointLabels$PtCol[pointLabels$Taxon == "Borhyaena_tuberata"] <- "#ca576c" #red - just to see position. 
pointLabels$PtCol[pointLabels$Family == "Canidae"] <- "#ffaa5c" #blue
pointLabels$PtCol[pointLabels$Taxon == "Canis_lupus"] <- "#233045" #navy - just to see position
pointLabels$PtCol[pointLabels$Taxon == "Andrewsarchus_mongoliensis"] <- "#72c496" #green - just to see position
pointLabels$Point <- 21
pointLabels$Point[pointLabels$Clade == "Metatheria"] <- 23
pointLabels$ID <- str_c(substr(pointLabels$Taxon,1,3), str_to_title(substr(sub(".*_", "", pointLabels$Taxon),1,3)) )
# For publication, we'll change those 'position' colours back to their clade colours and use text call-outs


# Gather mean value labels
meanLabels <- pointLabels
# This pulls out labels by species, and keeps the rest of the associated data columns
meanLabels <- meanLabels %>%
    distinct(Taxon, .keep_all = T)
row.names(meanLabels) <- meanLabels$Taxon
meanLabels <- meanLabels[order(meanLabels$Taxon, decreasing = F), ]
```

#### Skull
```{r Skull Set}
new.subset <-coords.subset(A = skullLmkSymm$symm.shape,
                           group = pointLabels$Taxon) ##THIS IS NOW ALPHABETICAL
meanCoords <- sapply(new.subset, 
                      mshape, 
                      simplify = "array") ##THIS IS NOW ALPHABETICAL



skullPCA <- gm.prcomp(meanCoords) 
skullPCPlot <- plot(skullPCA)
PCScores <- skullPCA$x[,1:10]
skullPlotData <- bind_cols(PCScores, meanLabels)

rm(new.subset, meanCoords, PCScores)

```

```{r Plot PC 1-2}
 svglite(filename = here::here("Figures", "PCA_FuncSkull.svg"),
         pointsize = 6,
        width = 3.5,
        height = 3.5)
plot(NULL,
     xlim = range(skullPlotData$Comp1),
     ylim = range(skullPlotData$Comp2),
     lwd = 0.5,
     asp = 1,
     xlab = skullPCPlot$plot.args$xlab,                       
     ylab = skullPCPlot$plot.args$ylab,                       
     main = "Functional Skull PCA")
abline(h = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 0.5)
abline(v = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 0.5)
points(skullPlotData$Comp2 ~ skullPlotData$Comp1, 
     pch = skullPlotData$Point, 
     col = "#000000", 
     bg = skullPlotData$PtCol, 
     cex = 2)
# text(skullPlotData$Comp1, skullPlotData$Comp2,  #for plotting species names
#      skullPlotData$ID,
#      cex=0.6,
#      pos=1,
#      offset = -0.2)
legend("bottomright",
       legend = c("Placentals", "Canids",
                  "Metatherians", "Thylacinidae"),
       pch = c(21, 21, 23, 23),
       col = c("#000000", "#000000", "#000000", "#000000"),
       pt.bg = c("#fff0e0", "#ffaa5c", "#e0f0ff", "#c87ef8"),
       bty = "n",
       pt.cex = 2,
       cex = 1,
       text.col = "black",
       horiz = F ,
       inset = c(0.00, 0.0))
# dev.off()
```

#### Rostrum
```{r Skull Set}
new.subset <-coords.subset(A = rostralLmkSymm$symm.shape,
                           group = pointLabels$Taxon) ##THIS IS NOW ALPHABETICAL
meanCoords <- sapply(new.subset, 
                      mshape, 
                      simplify = "array") ##THIS IS NOW ALPHABETICAL



rostPCA <- gm.prcomp(meanCoords) 
rostPCPlot <- plot(rostPCA)
PCScores <- rostPCA$x[,1:10]
rostPlotData <- bind_cols(PCScores, meanLabels)

rm(new.subset, meanCoords, PCScores)

```

```{r Plot PC 1-2}
 svglite(filename = here::here("Figures", "PCA_FuncRost.svg"),
         pointsize = 6,
        width = 3.5,
        height = 3.5)
plot(NULL,
     xlim = range(rostPlotData$Comp1),
     ylim = range(rostPlotData$Comp2),
     asp = 1,
     xlab = rostPCPlot$plot.args$xlab,                       
     ylab = rostPCPlot$plot.args$ylab,                       
     main = "Functional Rostral PCA")
abline(h = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 0.5)
abline(v = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 0.5)
points(rostPlotData$Comp2 ~ rostPlotData$Comp1, 
     pch = rostPlotData$Point, 
     col = "#000000", 
     bg = rostPlotData$PtCol, 
     cex = 2)
# text(rostPlotData$Comp1, rostPlotData$Comp2, #for plotting species names
#      rostPlotData$ID,
#      cex=0.6,
#      pos=1,
#      offset = -0.2)
legend("topright",
       legend = c("Placentals", "Canids",
                  "Metatherians", "Thylacinidae"),
       pch = c(21, 21, 23, 23),
       col = c("#000000", "#000000", "#000000", "#000000"),
       pt.bg = c("#fff0e0", "#ffaa5c", "#e0f0ff", "#c87ef8"),
       bty = "n",
       pt.cex = 2,
       cex = 1,
       text.col = "black",
       horiz = F ,
       inset = c(0.00, 0.0))
 dev.off()
```


#### Neurocranium
```{r Skull Set}
new.subset <-coords.subset(A = neuroLmkSymm$symm.shape,
                           group = pointLabels$Taxon) ##THIS IS NOW ALPHABETICAL
meanCoords <- sapply(new.subset, 
                      mshape, 
                      simplify = "array") ##THIS IS NOW ALPHABETICAL



neurPCA <- gm.prcomp(meanCoords) 
neurPCPlot <- plot(neurPCA)
PCScores <- neurPCA$x[,1:10]
neurPlotData <- bind_cols(PCScores, meanLabels)

rm(new.subset, meanCoords, PCScores)

```

```{r Plot PC 1-2}

 svglite(filename = here::here("Figures", "PCA_FuncNeur.svg"),
         pointsize = 6,
         width = 3.5,
         height = 3.5)
plot(NULL,
     xlim = range(neurPlotData$Comp1),
     ylim = range(neurPlotData$Comp2),
     asp = 1,
     xlab = neurPCPlot$plot.args$xlab,                       
     ylab = neurPCPlot$plot.args$ylab,                       
     main = "Functional Neurocranium PCA")
abline(h = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 0.5)
abline(v = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 0.5)
points(neurPlotData$Comp2 ~ neurPlotData$Comp1, 
     pch = neurPlotData$Point, 
     col = "#000000", 
     bg = neurPlotData$PtCol, 
     cex = 2)
# text(neurPlotData$Comp1, neurPlotData$Comp2, #for plotting species names
#      neurPlotData$ID,
#      cex=0.6,
#      pos=1,
#      offset = -0.2)
legend("bottomleft",
       legend = c("Placentals", "Canids",
                  "Metatherians", "Thylacinidae"),
       pch = c(21, 21, 23, 23),
       col = c("#000000", "#000000", "#000000", "#000000"),
       pt.bg = c("#fff0e0", "#ffaa5c", "#e0f0ff", "#c87ef8"),
       bty = "n",
       pt.cex = 2,
       cex = 1,
       text.col = "black",
       horiz = F ,
       inset = c(0.00, 0.0))
 dev.off()
```
