---
title: "pca_Devo"
author: "DSRovinsky"
date: "2023-05-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages}
library(geomorph)  # CRAN v4.0.10 
library(ape)       # CRAN v5.8-1 
library(tidyverse) # CRAN v2.0.0 
library(svglite)   # CRAN v2.2.2
library(here)      # CRAN v1.0.2 
```

```{r Load data}
# Load data produced in "GMM_GPA.Rmd"
load(here("Data", "Processed", "fnpLmkSymm.rda"))
load(here("Data", "Processed", "paLmkSymm.rda"))
load(here("Data", "Processed", "mesLmkSymm.rda"))

# Load the labels produced in "GMM_GPA.Rmd"
pointLabels <- readRDS(here("Data", "Processed", "pointLabels.rds"))

```

```{r Labels}
pointLabels$PtCol <- "#fff0e0"
pointLabels$PtCol[pointLabels$Clade == "Metatheria"] <- "#e0f0ff"
pointLabels$PtCol[pointLabels$Family == "Thylacinidae"] <- "#c87ef8" #purple
pointLabels$PtCol[pointLabels$Taxon == "Borhyaena_tuberata"] <- "#e0f0ff" #red - just to see position
pointLabels$PtCol[pointLabels$Family == "Canidae"] <- "#ffaa5c" #blue
pointLabels$PtCol[pointLabels$Taxon == "Canis_lupus"] <- "#ffaa5c" #navy - just to see position
pointLabels$PtCol[pointLabels$Taxon == "Andrewsarchus_mongoliensis"] <- "#fff0e0" #green - just to see position
pointLabels$Point <- 21
pointLabels$Point[pointLabels$Clade == "Metatheria"] <- 23
pointLabels$ID <- str_c(substr(pointLabels$Taxon,1,3), str_to_title(substr(sub(".*_", "", pointLabels$Taxon),1,3)) )

# for publication we'll change those 'positional' colours back to the clade colours and use text call outs

# Gather mean value labels
meanLabels <- pointLabels
# This pulls out labels by species, and keeps the rest of the associated data columns
meanLabels <- meanLabels %>%
    distinct(Taxon, .keep_all = T)
row.names(meanLabels) <- meanLabels$Taxon
meanLabels <- meanLabels[order(meanLabels$Taxon, decreasing = F), ]
```


```{r FNP Subset}
new.subset <-coords.subset(A = fnpLmkSymm$symm.shape,
                           group = pointLabels$Taxon) ##THIS IS NOW ALPHABETICAL
coordsFNP <- sapply(new.subset, 
                      mshape, 
                      simplify = "array") ##THIS IS NOW ALPHABETICAL

rm(new.subset)

pcaFNP <- gm.prcomp(coordsFNP) 
fnpPlot <- plot(pcaFNP)
pcaFNPscores <- pcaFNP$x[,1:10]
fnpPlotData <- bind_cols(pcaFNPscores, meanLabels)



```



```{r FNP PCA Plot}
svglite(filename = here::here("Figures", "PCA_DevoFNP.svg"),
        pointsize = 6,
        width = 3.5,
        height = 3.5)
plot(NULL,
     xlim = range(fnpPlotData$Comp1),
     ylim = range(fnpPlotData$Comp2),
     asp = 1,
     xlab = fnpPlot$plot.args$xlab,                       
     ylab = fnpPlot$plot.args$ylab,                       
     main = "FNP PCA")
abline(h = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 1.5)
abline(v = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 1.5)
points(fnpPlotData$Comp2 ~ fnpPlotData$Comp1, 
     pch = fnpPlotData$Point, 
     col = "#000000", 
     bg = fnpPlotData$PtCol, 
     cex = 1.5)
# text(fnpPlotData$Comp1, fnpPlotData$Comp2, #to show species
#      fnpPlotData$ID,
#      cex=0.6,
#      pos=1,
#      offset = -0.2)
legend("bottomleft", 
       legend = c("Placentals","Canids", 
                  "Metatherians", "Thylacinids"), 
       pch = c(21, 21, 23, 23),
       col = c("#000000", "#000000", "#000000", "#000000"), 
       pt.bg = c("#fff0e0", "#ffaa5c", "#e0f0ff", "#c87ef8"),
       bty = "n",
       pt.cex = 1.5, 
       cex = 0.7, 
       text.col = "black", 
       horiz = F ,
       inset = c(0.0, 0.0))
dev.off()
```

```{r PA Subset}
new.subset <-coords.subset(A = paLmkSymm$symm.shape,
                           group = pointLabels$Taxon) ##THIS IS NOW ALPHABETICAL
coordsPA <- sapply(new.subset, 
                      mshape, 
                      simplify = "array") ##THIS IS NOW ALPHABETICAL

rm(new.subset)

pcaPA <- gm.prcomp(coordsPA) 
paPlot <- plot(pcaPA)
pcaPAscores <- pcaPA$x[,1:10]
paPlotData <- bind_cols(pcaPAscores, meanLabels)

```

```{r PA PCA Plot}
svglite(filename = here::here("Figures", "PCA_DevoPA.svg"),
        pointsize = 6,
        width = 3.5,
        height = 3.5)
plot(NULL,
     xlim = range(paPlotData$Comp1),
     ylim = range(paPlotData$Comp2),
     asp = 1,
     xlab = paPlot$plot.args$xlab,                       
     ylab = paPlot$plot.args$ylab,                       
     main = "PA PCA")
abline(h = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 1.5)
abline(v = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 1.5)
points(paPlotData$Comp2 ~ paPlotData$Comp1, 
     pch = paPlotData$Point, 
     col = "#000000", 
     bg = paPlotData$PtCol, 
     cex = 1.5)
# text(paPlotData$Comp1, paPlotData$Comp2, #to show species
#      paPlotData$ID,
#      cex=0.6,
#      pos=1,
#      offset = -0.2)
legend("topright", 
       legend = c("Placentals","Canids", 
                  "Metatherians", "Thylacinids"), 
       pch = c(21, 21, 23, 23),
       col = c("#000000", "#000000", "#000000", "#000000"), 
       pt.bg = c("#fff0e0", "#ffaa5c", "#e0f0ff", "#c87ef8"),
       bty = "n",
       pt.cex = 1.5, 
       cex = 0.7, 
       text.col = "black", 
       horiz = F ,
       inset = c(0.0, 0.0))
dev.off()
```

```{r MES Subset}
new.subset <-coords.subset(A = mesLmkSymm$symm.shape,
                           group = pointLabels$Taxon) ##THIS IS NOW ALPHABETICAL
coordsMES <- sapply(new.subset, 
                      mshape, 
                      simplify = "array") ##THIS IS NOW ALPHABETICAL

rm(new.subset)


pcaMES <- gm.prcomp(coordsMES) 
mesPlot <- plot(pcaMES)
pcaMESscores <- pcaMES$x[,1:10]
mesPlotData <- bind_cols(pcaMESscores, meanLabels)

```

```{r MES PCA Plot}
svglite(filename = here::here("Figures", "PCA_DevoMES.svg"),
        pointsize = 6,
        width = 3.5,
        height = 3.5)
plot(NULL,
     xlim = range(mesPlotData$Comp1),
     ylim = range(mesPlotData$Comp2),
     asp = 1,
     xlab = mesPlot$plot.args$xlab,                       
     ylab = mesPlot$plot.args$ylab,                       
     main = "MES PCA")
abline(h = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 1.5)
abline(v = 0, 
       col = "#545454", 
       lty = "dashed", 
       lwd = 1.5)
points(mesPlotData$Comp2 ~ mesPlotData$Comp1, 
     pch = mesPlotData$Point, 
     col = "#000000", 
     bg = mesPlotData$PtCol, 
     cex = 1.5)
# text(mesPlotData$Comp1, mesPlotData$Comp2, #to show species
#      mesPlotData$ID,
#      cex=0.6,
#      pos=1,
#      offset = -0.2)
legend("topleft", 
       legend = c("Placentals","Canids", 
                  "Metatherians", "Thylacinids"), 
       pch = c(21, 21, 23, 23),
       col = c("#000000", "#000000", "#000000", "#000000"), 
       pt.bg = c("#fff0e0", "#ffaa5c", "#e0f0ff", "#c87ef8"),
       bty = "n",
       pt.cex = 1.5, 
       cex = 0.7, 
       text.col = "black", 
       horiz = F ,
       inset = c(0.0, 0.0))
dev.off()
```

#save mean partitions for later Wheatsheaf code
```{r}


load(here("Data", "Processed", "Partition_species_coords.rda"))

Partition_species_coords$FNP <- coordsFNP
Partition_species_coords$Pa <- coordsPA
Partition_species_coords$Mes <- coordsMES
 

save (Partition_species_coords,meanLabels, file=here("Data", "Processed", "Partition_species_coords.rda"))

```

