---
title: "04_02_Procrustes_Funct_Analyses_v2"
author: "DSRovinsky"
date: "`r Sys.Date()`"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gather up the data
```{r Packages}
library(geomorph)
library(shapes)
library(tidyverse)
library(ggplot2)
library(svglite)
library(here)
```


```{r Load data}
# Load GPA produced in "GMM_GPA.Rmd"
load(here("Data", "Processed", "skullLmkSymm.rda"))
load(here("Data", "Processed", "rostralLmkSymm.rda"))
load(here("Data", "Processed", "neuroLmkSymm.rda"))

# Load the labels produced in "GMM_GPA.Rmd"
pointLabels <- readRDS(here("Data", "Processed", "pointLabels.rds"))
# remove Nimbacinus dicksoni for Family comparisons
familyLabels <- pointLabels[!pointLabels$Taxon %in% "Nimbacinus_dicksoni",]
```


# ProcDistances between thylacine and comparative species
```{r Subset Coords}
# Here, we'll look at the Procrustes distances between the thylacine and several 
# interesting species (from a convergent evolution standpoint) 

# subset out the species coordinates
skullSpeciesCoords <- coords.subset(A = skullLmkSymm$symm.shape, group = pointLabels$Taxon)
rostralSpeciesCoords <- coords.subset(A = rostralLmkSymm$symm.shape, group = pointLabels$Taxon)
neuroSpeciesCoords <- coords.subset(A = neuroLmkSymm$symm.shape, group = pointLabels$Taxon)

#calculate their mean shapes
skullSpeciesMShape <- lapply(skullSpeciesCoords, mshape)
rostralSpeciesMShape <- lapply(rostralSpeciesCoords, mshape)
neuroSpeciesMShape <- lapply(neuroSpeciesCoords, mshape)


```


```{r Species' Procdist}
# Generate pair-wise Procrustes distances between the thylacine and each species' 
# mean shape in the total skull, rostral, and neurocranial datasets.

# Skull
skullProcDist <- data.frame(matrix(ncol = 2, nrow = 60))
colnames(skullProcDist) <- c("Species", "ProcDist")
skullProcDist$Species <- unique(pointLabels$Taxon)
skullProcDist <- skullProcDist[order(skullProcDist$Species),]

# Rostral
rostralProcDist <- data.frame(matrix(ncol = 2, nrow = 60))
colnames(rostralProcDist) <- c("Species", "ProcDist")
rostralProcDist$Species <- unique(pointLabels$Taxon)
rostralProcDist <- rostralProcDist[order(rostralProcDist$Species),]

# Neurocranial
neuroProcDist <- data.frame(matrix(ncol = 2, nrow = 60))
colnames(neuroProcDist) <- c("Species", "ProcDist")
neuroProcDist$Species <- unique(pointLabels$Taxon)
neuroProcDist <- neuroProcDist[order(neuroProcDist$Species),]
```

```{r Pdist calc}
# Skull
for (i in 1:length(skullSpeciesMShape)) {
  skullProcDist$ProcDist[i] <- procdist(skullSpeciesMShape$Thylacinus_cynocephalus, skullSpeciesMShape[[i]])
}

row.names(skullProcDist) <- skullProcDist$Species
skullProcDist <- skullProcDist[!row.names(skullProcDist) %in% "Thylacinus_cynocephalus",] # be a bit silly to compare itself

# Rostrum
for (i in 1:length(rostralSpeciesMShape)) {
  rostralProcDist$ProcDist[i] <- procdist(rostralSpeciesMShape$Thylacinus_cynocephalus, rostralSpeciesMShape[[i]])
}

row.names(rostralProcDist) <- rostralProcDist$Species
rostralProcDist <- rostralProcDist[!row.names(rostralProcDist) %in% "Thylacinus_cynocephalus",]

# Neurocranium
for (i in 1:length(neuroSpeciesMShape)) {
  neuroProcDist$ProcDist[i] <- procdist(neuroSpeciesMShape$Thylacinus_cynocephalus, neuroSpeciesMShape[[i]])
}

row.names(neuroProcDist) <- neuroProcDist$Species
neuroProcDist <- neuroProcDist[!row.names(neuroProcDist) %in% "Thylacinus_cynocephalus",]

##make table
rownames(skullProcDist)==rownames(neuroProcDist)
rownames(neuroProcDist)==rownames(rostralProcDist)

functional_procdists_table <- cbind(skullProcDist, rostralProcDist$ProcDist, neuroProcDist$ProcDist)
save(functional_procdists_table, file="./Data/Processed/functional_procdists_table.rda")


```


```{r Find Closest species}
# Arrange the datasets by decreasing Procrustes similarity (i.e., increasing Procrustes distance).
# This puts the species closest in shape to the thylacine at the top, ordered by their similarity.
# Pull out the top 20 species in each set (i.e., those with the smallest Procrustes distance from the thylacine)
# I picked 20 because it's roughly 1/3 of the dataset. We need a way to qualitatively say whether a species' shape
# is 'close' to the thylacine, but we don't want to be either too arbitrary, or too cherry-picking.
# If the species is closer to the thylacine than 2/3 of the dataset, that sounds pretty good to me.

topSkullDistance <- skullProcDist[order(skullProcDist$ProcDist, decreasing = F),]
topSkullDistance <- topSkullDistance[1:20,]

topRostralDistance <- rostralProcDist[order(rostralProcDist$ProcDist, decreasing = F),]
topRostralDistance <- topRostralDistance[1:20,]

topNeuroDistance <- neuroProcDist[order(neuroProcDist$ProcDist, decreasing = F),]
topNeuroDistance <- topNeuroDistance[1:20,]

topSpecies <- rbind.data.frame(topSkullDistance, 
                                 topRostralDistance, 
                                 topNeuroDistance)
row.names(topSpecies) <- c(1:nrow(topSpecies)) # because it inherited the species' names
topSpecies <- droplevels(topSpecies) # there are species that aren't represented here

# Now find who appears most frequently (i.e., n > 1) in the top 1/3 of the all the datasets
# i.e., a species has to be closer to the thylacine than 2/3 of the species sampled in 
# MORE THAN ONE partition, e.g., across BOTH the rostrum and neurocranium, etc.
topSpecies <- data.frame(table(topSpecies$Species)) # quick calc frequency of appearance
topSpecies <- topSpecies[order(topSpecies$Freq, decreasing = T),]
topSpecies <- topSpecies[topSpecies$Freq > 1,] # select those that appear more than once

# We found them! Turns out there's 19 species. These will be plotted below. :) 

   
topNames <- as.vector(topSpecies$Var1)
topNames

rm(topSkullDistance,
   topRostralDistance,
   topNeuroDistance,
   topSpecies)
```


```{r Gather for ggplot}
#gather that all up so we can look at it
# re-order the Procrustes distance results we obtained above by species to they are all in the same order
skullProcDist <- skullProcDist[order(skullProcDist$Species),]
rostralProcDist <- rostralProcDist[order(rostralProcDist$Species),]
neuroProcDist <- neuroProcDist[order(neuroProcDist$Species),]

procDistSpecies <- cbind(skullProcDist, rostralProcDist$ProcDist, neuroProcDist$ProcDist)
colnames(procDistSpecies) <- c("Species", "Skull_Pdist", "Rostral_Pdist", "Neuro_Pdist")
rownames(procDistSpecies) <- procDistSpecies$Species
procDistSpecies <- procDistSpecies[topNames,]
procDistSpecies <- droplevels(procDistSpecies)
procDistSpecies$mean_Pdist <- rowMeans(procDistSpecies[,c(2:4)])
procDistSpecies <- procDistSpecies[order(procDistSpecies$Skull_Pdist, decreasing = T),]


# gather it so that ggplot can understand it
plotDataSpecies <- gather(procDistSpecies, Set, Pdist, Skull_Pdist:Neuro_Pdist, factor_key=TRUE)
# round the Pdist just for easy visual comparison
roundDistSpecies <- round(procDistSpecies[,c(2:5)], 3)

# clean up environment
rm(skullSpeciesCoords,
   rostralSpeciesCoords,
   neuroSpeciesCoords,
   skullProcDist, 
   rostralProcDist, 
   neuroProcDist,
   skullSpeciesMShape,
   rostralSpeciesMShape,
   neuroSpeciesMShape)
```


```{r Species ProcDistance plot}
svglite(filename = here::here("Figures", "Procdist_FuncSpecies_v2.svg"),
        pointsize = 6, height = 4, width = 3.6)
ggplot(data = plotDataSpecies, aes(y = Pdist, 
                                   x = fct_inorder(Species), 
                                   colour = Set)) +
    geom_linerange(aes(x = fct_inorder(Species), 
                       ymin = 0, ymax = Pdist, 
                       colour = Set), 
                   position = position_dodge(width = 0.5), 
                   size = 0.5)+
    scale_colour_manual(name = "Landmark Set",
                        labels = c("Skull", "Rostrum", "Neurocranium"),
                        values = c("#233045", "#72c496", "#ba5800")) +
    geom_point(aes(x = fct_inorder(Species), 
                   y = Pdist, 
                   shape = Set, 
                   fill = Set),
               position = position_dodge(width = 0.5), 
               size = 3) +
    scale_shape_manual(name = "Landmark Set",
                       labels = c("Skull", "Rostrum", "Neurocranium"),
                       values = c(21,24,22)) +
    scale_fill_manual(name = "Landmark Set",
                      labels = c("Skull", "Rostrum", "Neurocranium"),
                      values = c("#233045", "#72c496", "#ba5800")) +
    coord_flip() +
    ylab("Procrustes distance from thylacine v2") +
    xlab(NULL) +
    theme(panel.background = element_rect(fill = "#ffffff", colour = "#545454"),
        panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(linetype = "dotted", colour = "#bfbfbf"),
        panel.grid.minor.x = element_line(linetype = "dotted", colour = "#bfbfbf"),
        axis.text.x = element_text(size = 8),
        axis.text.y = element_text(size = 8),
        legend.position = "bottom") 
dev.off()
```


# Quick descriptives
```{r Summary & Q1}
summSpecies <- as.table(summary(roundDistSpecies))
# the following extracts the value in the second row of the table, 1st, 2nd, 3rd column respectively
skullQ1 <- summSpecies[[2,1]] # skull Q1
rostralQ1 <- summSpecies[[2,2]] # Rostral Q1
neuroQ1 <- summSpecies[[2,3]] # Neuro Q1
```

```{r Q1 Species}
# pull the rows for the cases that are less than or equal to the respective Q1 value
Q1SkullSpecs <- roundDistSpecies[roundDistSpecies$Skull_Pdist <= 0.1220, ]
Q1RostralSpecs <- roundDistSpecies[roundDistSpecies$Rostral_Pdist <= 0.1510, ]
Q1NeuroSpecs <- roundDistSpecies[roundDistSpecies$Neuro_Pdist <= 0.1710, ]
```