---
title: "Rosette_Analysis"
author: "DSRovinsky"
date: "2023-01-17"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load packages}
library(geomorph) # CRAN v4.0.7
library(ape)      # CRAN v5.8
library(geiger)   # CRAN v2.0.11
library(nlme)     # CRAN v3.1-164
library(dplyr)    # CRAN v1.1.4
library(svglite)  # CRAN v2.1.3
library(here)     # CRAN v1.0.1
```

```{r Functions}
source(here::here("Functions", "Fun.R"))
```


#Creating interlandmark distances: first read in coordinates, then find inter-landmark distances, then average these by species
```{r}

load(here("Data", "Processed", "rawPoints.rda"))
pointLabels <- readRDS(here("Data", "Processed", "pointLabels.rds"))

#Just checking that the order and content of point labels and raw points are the same - all good
rawPoints$labels==pointLabels

# Load phylogeny: this is the composite tree from Rovinsky et al., 2021, with the fossil taxa added
phyTree <- read.tree(here::here("Data", "phyloGMM.tre"))

# matrix of landmarks to measure
# here we are going to measure the distance between lmks 6 & 7, and between lmks 68 & 73
lmks <- matrix(c(6,7, 68,73), 
               ncol = 2, 
               byrow = TRUE, 
               dimnames = list(c("Canine", "Pinch"),
                               c("start", "end")))

# calculate the distances for the  lmks for all specimens
linearDists_allspecies <- interlmkdist(rawPoints$coords, lmks) 

#now average these for each species. I checked a couple of species manually and all is good. Making it readable for the next step but make sure this chunk gets run only once because it's deleting a column!
linearDists <- aggregate(linearDists_allspecies, by=list(pointLabels$Taxon), FUN=mean)
rownames(linearDists) <- linearDists$Group.1
linearDists <- linearDists[,-1]

```


```{r Set up data for analysis}


# get pointLabels for each species
taxaSet <- unique(pointLabels) %>% arrange(Taxon)

#Just checking!
taxaSet$Taxon == rownames(linearDists)

# combine data
dataRosette <- as.data.frame(cbind(taxaSet, log10(linearDists)))
row.names(dataRosette) <- dataRosette$Taxon
# re-order data to tree tip order
dataRosette <- dataRosette[order(match(dataRosette[,3],phyTree$tip.label)),]
name.check(phy = phyTree, 
           data = dataRosette, 
           data.names = dataRosette$Taxon)
plotData <- dataRosette
```

```{r PGLS data}
phyPGLS <- drop.tip(phy = phyTree, tip = c("Andrewsarchus_mongoliensis", "Thylacinus_cynocephalus"))
specList <- as.character(phyPGLS$tip.label)
dataPGLS <- dataRosette[which(dataRosette$Taxon != c("Andrewsarchus_mongoliensis", "Thylacinus_cynocephalus")),]
dataPGLS <- droplevels(dataPGLS)
name.check(phy = phyPGLS, 
           data = dataPGLS, 
           data.names = dataPGLS$Taxon)

# phylogeny includes fossils (is not ultrametric) so we need to add weights
tW <- diag(vcv(phyPGLS)) # tree weights
```


```{r Model fit}
fit1 <- gls(Pinch ~ Canine, 
               data = dataPGLS, 
               correlation = corBrownian(value = 1, 
                                      phy = phyPGLS,
                                      form = ~specList),
               method = "REML",
               weights = varFixed(~tW))

fit2 <- gls(Pinch ~ Canine, 
               data = dataPGLS, 
               correlation = corPagel(value = 1, 
                                      phy = phyPGLS, 
                                      fixed = FALSE,
                                      form = ~specList),
               method = "REML",
               weights = varFixed(~tW))

fit3 <- gls(Pinch ~ Canine, 
               data = dataPGLS, 
               correlation = corBrownian(value = 1, 
                                      phy = phyPGLS,
                                      form = ~specList),
               method = "ML",
               weights = varFixed(~tW))

fit4 <- gls(Pinch ~ Canine, 
               data = dataPGLS, 
               correlation = corPagel(value = 1, 
                                      phy = phyPGLS, 
                                      fixed = FALSE,
                                      form = ~specList),
               method = "ML",
               weights = varFixed(~tW))
anova(fit1, fit2)
anova(fit3, fit4)
```

```{r PGLS Regression}
rosettePGLS <- fit4

L = rosettePGLS$modelStruct$corStruct[1]

rosetteCI <- gls.ci(Y = as.numeric(dataPGLS$Pinch),
                    X = as.numeric(dataPGLS$Canine),
                    Sigma = vcv(corPagel(value = L,
                                       phy = phyPGLS,
                                       fixed = TRUE,
                                       form = ~specList)))


# 95% prediction interval without the thylacine and Andrewsarchus

rosettePI <- gls.pi(Y = as.numeric(dataPGLS$Pinch),
                    X = as.numeric(dataPGLS$Canine),
                    Sigma = vcv(corPagel(value = L,
                                       phy = phyPGLS,
                                       fixed = TRUE,
                                       form = ~specList)),
                  k = 2)

```

```{r Full PGLS}
specList2 <- as.character(phyTree$tip.label)
tWFull <- diag(vcv(phyTree))
fullPGLS <- gls(Pinch ~ Canine, 
               data = dataRosette, 
               correlation = corPagel(value = 1, 
                                      phy = phyTree, 
                                      fixed = FALSE,
                                      form = ~specList2),
               method = "ML",
               weights = varFixed(~tWFull))
```


```{r Plot data}
plotData$Residuals <- fullPGLS$residuals
plotData <- plotData[order(plotData$Residuals),]
plotData$xNum <- 1:nrow(plotData)

#The colour scheme is the result of some experimentation and not optimised code-wise for this final published plot
plotData$StemCol <- "#cccccc" # 20% gray
plotData$StemCol[plotData$Family == "Canidae"] <- "#ffaa5c" # yellow
plotData$StemCol[plotData$Taxon == "Canis_lupus"] <- "#ffaa5c" # navy - to see position
plotData$StemCol[plotData$Clade == "Metatheria"] <- "#e0f0ff" # blue
plotData$StemCol[plotData$Taxon == "Thylacinus_cynocephalus"] <- "#c87ef8" # electric purple
plotData$StemCol[plotData$Taxon == "Nimbacinus_dicksoni"] <- "#e6e6b8" # cream - to see position
plotData$StemCol[plotData$Taxon == "Borhyaena_tuberata"] <- "#ca576c" # red - to see position
plotData$StemCol[plotData$Taxon == "Andrewsarchus_mongoliensis"] <- "#72c496" #  green - to see position

plotData$PtCol <- "#f0eef0" # off-white
plotData$PtCol[plotData$Family == "Canidae"] <- "#ffaa5c" 
plotData$PtCol[plotData$Taxon == "Canis_lupus"] <- "#ffaa5c" # to see position
plotData$PtCol[plotData$Taxon == "Crocuta_crocuta"] <- "#f0eef0" # to see position
plotData$PtCol[plotData$Clade == "Metatheria"] <- "#e0f0ff"
plotData$PtCol[plotData$Taxon == "Thylacinus_cynocephalus"] <- "#c87ef8"
plotData$PtCol[plotData$Taxon == "Nimbacinus_dicksoni"] <- "#c87ef8" # cream - to see position
plotData$PtCol[plotData$Taxon == "Borhyaena_tuberata"] <- "#e0f0ff" # red - to see position
plotData$PtCol[plotData$Taxon == "Andrewsarchus_mongoliensis"] <- "#72c496" # green - to see position

plotData$PtSet <- 21
plotData$PtSet[plotData$Clade == "Metatheria"] <- 23

# For publication, we'll change those 'position' colours back to their clade colours and use text call-outs

```

```{r Residual plot}
range(plotData$Residuals) # -0.1351506  0.1311476

plot(NULL,
     xlim = c(0,61), # just a little more so the plot is nice and roomy
     ylim = c(-0.12, 0.18), # just a little larger so the plot is nice and roomy
     xlab = "Species",                       
     ylab = "PGLS Residuals",  
     xaxt = "n",
     main = "log10 Rostral pinch ~ log10 Width at canines")
abline(h = 0, col = "#808080", lwd = 0.5, lty = "dotted")
arrows(x0 = plotData$xNum, x1 = plotData$xNum,
       y0 = 0, y1 = plotData$Residuals, # give the axis a little breathing room at y0
       code = 3, length = 0, lwd = 2,
       col = plotData$StemCol)
points(plotData$Residuals,
     pch = plotData$PtSet,
     col = "#000000",
     bg = plotData$PtCol,
     cex = 2)
legend("topleft", 
       legend = c("Placentals", "Canids", "Metatherians",  "Thylacinids"), 
       pch = c(21, 21, 23, 23),
       col = "#000000",
       pt.bg = c("#f0eef0", "#ffaa5c", "#e0f0ff", "#c87cf8"),
       bty = "n", 
       pt.cex = 2, 
       cex = 0.8, 
       text.col = "black", 
       horiz = F , 
       inset = c(0.01, 0.0))
```

```{r Regression plot}
 svglite(filename = here::here("Figures", "rosette_Regression.svg"), height = 5, width = 6)


plot(NULL,
     xlim = range(plotData$Canine), # just a little more so the plot is nice and roomy
     ylim = range(plotData$Pinch), # just a little larger so the plot is nice and roomy
     xlab = "Log10 interLmk width at canine",                       
     ylab = "Log10 interLmk width at rostral 'pinch'",  
     #main = "Rosette PGLS Regression"
     )
polygon(c(rosettePI$PI.plot$X, rev (rosettePI$PI.plot$X)), 
        c(rosettePI$PI.plot$Lower2.5, rev(rosettePI$PI.plot$Upper2.5)), 
        col = "#e5e5e5", 
        border = NA )
abline(a = fullPGLS$coefficients[1], 
       b = fullPGLS$coefficients[2], 
       lty = "longdash",
       lwd = 2, 
       col = "red")
lines(rosetteCI$CI.plot$X, 
      rosetteCI$CI.plot$Lower2.5,
      lty = 3)
lines(rosetteCI$CI.plot$X, 
      rosetteCI$CI.plot$Upper2.5,
      lty = 3)
abline(a = rosettePGLS$coefficients[1], 
       b = rosettePGLS$coefficients[2], 
       lty = "solid",
       lwd = 2, 
       col = "black")
points(y = plotData$Pinch, x = plotData$Canine,
              pch = plotData$PtSet,
              col = "#000000",
              bg = plotData$PtCol,
              cex = 1.5,
              xlab = "Body Mass (Log10 g)",                       
              ylab = "Log10 Centroid size",                       
              main = "Total set Csize")
legend("bottomright",
       legend = c("Placentals", "Canids", "Metatherians",  "Thylacinids"),
       pch = c(21, 21, 23, 23),
       col = "#000000",
       pt.bg = c("#f0eef0", "#ffaa5c", "#e0f0ff", "#c87cf8"),
       bty = "n",
       pt.cex = 1.1,
       cex = 0.8,
       text.col = "black",
       horiz = F ,
       inset = c(0.01, 0.0), 
       ncol=2, 
       x.intersp=2,
       y.intersp=1.2)
box(col = "#000000")
 dev.off()
```


