---
title: "IOF_DSR"
author: "DSRovinsky"
date: '2022-07-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Manipulate data
```{r Load packages}
library(ape)       # CRAN v5.8-1
library(geiger)    # CRAN v2.0.11
library(tidyverse) # CRAN v2.0.0
library(nlme)      # CRAN v3.1-168
library(svglite)   # CRAN v2.2.1
library(here)      # CRAN v1.0.1
```

```{r Functions}
source(here::here("Functions", "Fun.R"))
```


```{r Get some data}
rawData <- read.csv(here::here("Data", "IOF_Data_Muchlinski.csv"))

# data is a combination of Muchlinski, 2010 (doi:10.1016/j.jhevol.2010.01.012) and 
# Milne et al., 2021 (doi:10.1002/ar.24683) with new specimens (e.g., the fossil taxa) added

# This tree is pruned down from a Maximum Clade Compatibility (MCC) tree from 1,000 trees 
# sampled from the dataset of Upham et al., (2019; doi:10.1371/journal.pbio.3000494). 
# Data downloaded from https://vertlife.org/
pruned_MCC <- read.tree(here::here("Data", "pruned_MCC.tre"))
treeTips <- read.csv(here::here("Data", "Tree_tips.csv")) # .csv of the tips for each dataset


```

```{r Data manipulation}
# Do some dataframe manipulation
workData <- rawData[,1:6]
# These PtSets seem suspicious to me. Get them outta here!
workData <- workData[- which(workData$Species == "Tarsipes_rostratus"),]
workData <- workData[- which(workData$Species == "Ommatophoca_rossii"),]

workData$Group[workData$Group_dasyurids == "Pinniped"] <- "Placental" # these categories aren't needed for us
workData$Group[workData$Group_dasyurids == "Fissiped"] <- "Placental" # these categories aren't needed for us
workData$Group[workData$Group == "Marsupial"] <- "Metatheria" # these categories aren't needed for us
workData$Group[workData$Group_dasyurids == "Sparassodonta"] <- "Metatheria" # these categories aren't needed for us

workData$log_GM <- log10(workData$GM_mean)
workData$log_IOF <- log10(workData$IOF_mean)
workData$log_Mass <- log10(workData$Mass_mean)

workData$ID <- str_c(substr(workData$Species,1,3), str_to_title(substr(sub(".*_", "", workData$Species),1,3)) )

# prune the MCCtree to the species in the dataset
muchlinskiTips <- as.data.frame(treeTips[,5:6])
muchlinskiTips <- muchlinskiTips[- which(muchlinskiTips[,2] == "Tarsipes_rostratus"),]
muchlinskiTips <- muchlinskiTips[- which(muchlinskiTips[,2] == "Ommatophoca_rossii"),]
muchlinskiTips <- na.omit(muchlinskiTips$Tips3)
 
muchlinskiTree <- keep.tip(pruned_MCC, muchlinskiTips)

# Upham et al. did not include F. silvestris, but the clade containing F. bieti is likely the sister clade
# to that containing F. silvestris to the exclusion of the other Felis spp. in the tree (F. chaus), 
# so the position of F. bieti can be substituted here for F. silvestris
muchlinskiTree$tip.label[139] <- "Felis_silvestris"

rm(muchlinskiTips, pruned_MCC, treeTips)

```

```{r Convex hulls}
# Generate convex hulls around the PtSets
marsupialHull1 <- workData[c(which(workData$Group_dasyurids == "Marsupial"), which(workData$Group_dasyurids == "Dasyuromorphia")),]
marsupialHull <- workData[which(workData$Group == "Metatheria"),]
placentalHull <- workData[which(workData$Group == "Placental"),]


# metatheriaHull <- metatheriaHull[-which(metatheriaHull$Species == "Thylacinus_cynocephalus"),] # just for show
marsupialHull <- cbind(marsupialHull1$log_Mass, marsupialHull1$log_IOF)
placentalHull <- cbind(placentalHull$log_Mass, placentalHull$log_IOF)


mHpts <- chull(marsupialHull)
mHpts <- c(mHpts, mHpts[1])

pHpts <- chull(placentalHull)
pHpts <- c(pHpts, pHpts[1])
```

```{r IOF Plot set up}
# PtCols and pch values for easy plotting
IOFplotData <- workData

IOFplotData$PtCol <- "#fff0e0"
IOFplotData$PtCol[IOFplotData$Group == "Metatheria"] <- "#e0f0ff" # blue
IOFplotData$PtCol[IOFplotData$Species == "Thylacinus_cynocephalus"] <- "#c87ef8" # electric purple
IOFplotData$PtCol[IOFplotData$Species == "Nimbacinus_dicksoni"] <- "#c87ef8" # dark purple - to see position
IOFplotData$PtCol[IOFplotData$Species == "Borhyaena_tuberata"] <- "#ca576c" # red - to see position
IOFplotData$PtCol[IOFplotData$Species == "Prothylacinus_patagonicus"] <- "#ca576c" # red - to see position
#IOFplotData$PtCol[IOFplotData$Species == "Canis_lupus"] <- "#233045" # navy - to see position
IOFplotData$PtCol[IOFplotData$Group_dasyurids == "Dasyuromorphia"] <-"skyblue4"


IOFplotData[,"PtSet"] <- NA
IOFplotData$PtSet[IOFplotData$Group == "Placental"] <- 21
IOFplotData$PtSet[IOFplotData$Group == "Metatheria"] <- 23


```

# Plot
```{r IOF Plot}
# svglite(filename = here::here("Figures", "IOF_Mass_v3.svg"),
        # height = 5, width = 6)
plot(NULL,
     xlim = range(IOFplotData$log_Mass),
     ylim = range(IOFplotData$log_IOF),
     xlab = "log10 Body Mass (g)",                       
     ylab = "log10 IOF (mm2)")
polygon(placentalHull[pHpts, ],
        col = adjustcolor("#f9dec1", alpha.f = 0.33))
polygon(marsupialHull[mHpts, ],
        col = adjustcolor("#1680a4", alpha.f = 0.33))
points(IOFplotData$log_Mass, IOFplotData$log_IOF,
       pch = IOFplotData$PtSet,
       col = "#000000",
       bg = IOFplotData$PtCol,
       cex = 1.5)
# text(IOFplotData$log_Mass, IOFplotData$log_IOF,  #for plotting species names
#      IOFplotData$ID,
#       cex=0.6,
#       pos=1,
#       offset = -0.6)
legend("topleft", 
       legend = c("Placentals", "Marsupials", "Dasyuromorphians","Sparassodonts", "Thylacinids"), 
       pch = c(21, 23, 23, 23, 23),
       col = c("#000000", "#000000", "#000000"),
       pt.bg = c("#fff0e0", "#e0f0ff","skyblue4", "#ca576c","#c87ef8"), 
       bty = "n", 
       pt.cex = 2, 
       cex = 1, 
       text.col = "black", 
       horiz = F , 
       inset = c(0.01, 0.0))
#dev.off()
```

```{r PGLS data}
# tip order the data frame

# pglsData <- workData[,c(1:2,7:8)] # get rid of the columns where Prothylacinus throws an NA
pglsData <- IOFplotData
pglsData <- pglsData[order(match(pglsData[,1], muchlinskiTree$tip.label)),]
specList <- as.character(pglsData$Species)

```

```{r PGLS regression}
iofPGLS <- gls(log_IOF ~ log_Mass, 
               data = pglsData, 
               correlation = corPagel(value = 1, 
                                      phy = muchlinskiTree, 
                                      fixed = FALSE,
                                      form = ~specList),
               method = "ML")

summary(iofPGLS)
```

```{r PGLS regression plot}
plot(NULL,
     xlim = range(pglsData$log_Mass), # just a little more so the plot is nice and roomy
     ylim = range(pglsData$log_IOF), # just a little larger so the plot is nice and roomy
     xlab = "Log10 mass (g)",                       
     ylab = "Log10 IOF (mm2)",  
     main = "IOF PGLS Regression")
abline(a = iofPGLS$coefficients[1], 
       b = iofPGLS$coefficients[2], 
       lty = "dashed",
       lwd = 2, 
       col = "#333333")
points(pglsData$log_IOF ~ pglsData$log_Mass,
              pch = pglsData$PtSet,
              col = "#000000",
              bg = pglsData$PtCol,
              cex = 1.5)
```

# Marsupial-only set

```{r Marsupial data manipulation}
tempData <- IOFplotData
tempData <- tempData[order(match(tempData[,1], muchlinskiTree$tip.label)),]
fullData <- tempData[which(tempData$Group == "Metatheria"),][3:74,] #Taking out Prothylacinus and Borhyaena
pglsData <- fullData[- which(fullData$Species == "Thylacinus_cynocephalus"),]
rm(tempData)

plot(muchlinskiTree, cex = 0.5, adj = 0.8)
tiplabels(frame = "none", cex = 0.5, adj = -1)

marsupTree <- keep.tip(muchlinskiTree, c(3:74)) # remove non-marsupial tips (i.e. delete Prothylacinus and Borhyaena)
plot(marsupTree, cex = 0.5, adj = 0.8) # check
treePGLS <- drop.tip(marsupTree, "Thylacinus_cynocephalus")
plot(treePGLS, cex = 0.5, adj = 0.8) # check

# tip order the data frame
pglsData <- pglsData[order(match(pglsData[,1], treePGLS$tip.label)),]
specList <- as.character(treePGLS$tip.label)

name.check(phy = treePGLS, 
           data = pglsData, 
           data.names = pglsData$Species)
```

```{r Model fit}
tW <- diag(vcv(treePGLS)) # tree weights since we have fossils
fit1 <- gls(log_IOF ~ log_Mass, 
            data = pglsData, 
            correlation = corBrownian(value = 1, 
                                      phy = treePGLS,
                                      form = ~specList),
            weights = varFixed(~tW),
            method = "ML")

fit2 <- gls(log_IOF ~ log_Mass, 
            data = pglsData, 
            correlation = corPagel(value = 1, 
                                      phy = treePGLS, 
                                      fixed = FALSE,
                                      form = ~specList),
            weights = varFixed(~tW),
            method = "ML")
fit3 <- gls(log_IOF ~ log_Mass, 
            data = pglsData, 
            correlation = corBrownian(value = 1, 
                                      phy = treePGLS,
                                      form = ~specList),
            weights = varFixed(~tW),
            method = "REML")

fit4 <- gls(log_IOF ~ log_Mass, 
            data = pglsData, 
            correlation = corPagel(value = 1, 
                                      phy = treePGLS, 
                                      fixed = FALSE,
                                      form = ~specList),
            weights = varFixed(~tW),
            method = "REML")

anova(fit1, fit2)
anova(fit3, fit4)
plot(fit2,
     resid(., type = "n")~fitted(.),
     main = "Normalized Residuals v Fitted Values",
     abline = c(0,0), col = "black")
res <- resid(fit2, type="n")
qqnorm(res)
qqline(res)
```


```{r Marsupial PGLS regression}
iofPGLS <- fit2
rm(fit1, fit2, fit3, fit4)


L = iofPGLS$modelStruct$corStruct[1]
# 95% confidence interval for the PGLS line
pglsCI <- gls.ci(Y = pglsData$log_IOF, 
                  X = pglsData$log_Mass, 
                  Sigma = vcv(corPagel(value = L, 
                                      phy = treePGLS,
                                      fixed = TRUE,
                                      form = ~specList)))

# 95% prediction interval for the PGLS line
pglsPI <- gls.pi(Y = pglsData$log_IOF, 
                  X = pglsData$log_Mass, 
                  Sigma = vcv(corPagel(value = L, 
                                      phy = treePGLS,
                                      fixed = TRUE,
                                      form = ~specList)),
                  k = 1)


```

```{r Full PGLS}
fullData <- fullData[order(match(fullData[,1], marsupTree$tip.label)),]
specList2 <- as.character(marsupTree$tip.label)
name.check(phy = marsupTree, 
           data = fullData, 
           data.names = fullData$Species)
tW2 <- diag(vcv(marsupTree))

fullPGLS <- gls(log_IOF ~ log_Mass, 
            data = fullData, 
            correlation = corPagel(value = 1, 
                                      phy = marsupTree, 
                                      fixed = FALSE,
                                      form = ~specList2),
            weights = varFixed(~tW2),
            method = "ML")
```


```{r Residual data}
fullData$Residuals <- fullPGLS$residuals

fullData$PtCol <- "#e0f0ff"
fullData$PtCol[fullData$Species == "Thylacinus_cynocephalus"] <- "#c87cf8"
# fullData$PtCol[fullData$Species == "Sarcophilus_harrisii"] <- "#2e474d"

fullData$barCol <- "#cccccc"
fullData$barCol[fullData$Species == "Thylacinus_cynocephalus"] <- "#c87cf8"

fullData <- fullData[order(fullData$Residuals),]
fullData$xNum <- 1:nrow(fullData)
range(fullData$Residuals) # range for the plot: -0.7032064  0.5800534
```

```{r PGLS Regression plot}
 #svglite(filename = here::here("Figures", "IOF_MarsupialOnly.svg"),
     # height = 5, width = 6)

plot(NULL,
     xlim = range(fullData$log_Mass), # just a little more so the plot is nice and roomy
     ylim = range(fullData$log_IOF), # just a little larger so the plot is nice and roomy
     xlab = "Log10 mass (g)",                       
     ylab = "Log10 IOF (mm2)",  
     main = "Marsupial-only IOF PGLS Regression")
polygon(c(pglsPI$PI.plot$X, rev (pglsPI$PI.plot$X)), 
        c(pglsPI$PI.plot$Lower2.5, rev(pglsPI$PI.plot$Upper2.5)), 
        col = "#e5e5e5", 
        border = NA )

lines(pglsCI$CI.plot$X, 
      pglsCI$CI.plot$Lower2.5,
      lty = 3)
lines(pglsCI$CI.plot$X, 
      pglsCI$CI.plot$Upper2.5,
      lty = 3)
abline(a = iofPGLS$coefficients[1], 
       b = iofPGLS$coefficients[2], 
       lty = "solid",
       lwd = 2, 
       col = "#000000")
abline(a = fullPGLS$coefficients[1], 
       b = fullPGLS$coefficients[2], 
       lty = "longdash",
       lwd = 2, 
       col = "#FF0000")
points(y = fullData$log_IOF, x = fullData$log_Mass,
              pch = fullData$PtSet,
              col = "#000000",
              bg = fullData$PtCol,
              cex = 1.5)
lines(x= c(3.9,fullData$log_Mass[which(fullData$Species=="Thylacinus_cynocephalus")]-0.02), 
      y=c(1.5, fullData$log_IOF[which(fullData$Species=="Thylacinus_cynocephalus")]-0.02), 
      lwd=1.5 )
text(3.3, 1.5, 
     "Thylacinus cynocephalus", 
     font=3)
lines(x= c(3.5,fullData$log_Mass[which(fullData$Species=="Sarcophilus_harrisii")]-0.02), 
      y=c(1.05, fullData$log_IOF[which(fullData$Species=="Sarcophilus_harrisii")]-0.02), 
      lwd=1.5 )
text(3, 1, 
     "Sarcophilus harrisii", 
     font=3)
box(col = "#000000")

# dev.off()
```
